# Settings section
settings:
  # Changes name of mob to custom when mob is spawned in enabled worlds.
  # DEFAULT: true
  set-mob-name-on-spawn: true
  # Changes all names of mobs to custom when chunk is loaded in enabled worlds.
  # DEFAULT: true
  set-mob-name-on-chunk-load: true
  # Disabled worlds
  # Names of mobs from these worlds will not be changed.
  disabled-worlds:
  - 'disabled_world'
#Mobs section
mobs:
  # EXAMPLE
  # --------------------
  # cow:
  #   force-rename: false
  #   custom-names:
  #   - '&7Cow'
  # zombie:
  #   custom-names:
  #   - '&7Zombie'
  # --------------------
  # Mobs 1.13: 
  # armor_stand, bat, blaze, boat, cave_spider, chicken, cod, cow, creeper, dolphin, donkey, elder_guardian, 
  # enderman, endermite, evoker, giant, guardian, horse, husk, illusioner, iron_golem, llama, magma_cube, mule, 
  # mushroom_cow, ocelot, parrot, phantom, pig, pig_zombie, polar_bear, pufferfish, rabbit, salmon, sheep, shulker, 
  # silverfish, skeleton, skeleton_horse, slime, snowman, spider, squid, stray, tropical_fish, turtle, vex, villager, 
  # vindicator, witch, wither, wither_skeleton, wolf, zombie, zombie_horse, zombie_villager
  #
  sheep:
    # Change mob name to custom even though the mob already has a name
    # WARNING! This can change names of pets!
    # Not required in configuration
    # Can be "buggy" with more custom names!
    # DEFAULT: false
    force-change: true
    custom-names:
    - '&7Sheep &c<3'
  skeleton:
    custom-names:
    - '&7Skeleton'
