name: CustomMobsNames
main: com.wazustudio.spigot.custommobsnames.Main
version: 1.0.1
author: WazuStudio
website: https://wazustudio.com
description: Custom Name for Mobs
depend: []
load: STARTUP
commands:
  custommobsnames:
    description: Main command
permissions:
  custommobsnames.reload:
    description: Permission for /custommobsnames reload
     
